baseURL = "https://xenodochial-einstein-7a9b14.netlify.app/"
languageCode = "en-us"
title = "Ella's Hugo Site"
theme = "hugo-theme-hello-friend-ng-master"

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.3"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[params]
[[menu.main]]
name = "Introduction"
weight = 1
url = "/introduction/"

[[menu.main]]
name = "Resources"
weight = 2
url = "/Dresources/"

[[menu.main]]
name = "Walkthrough"
weight = 3
url = "/Dwalkthrough/"

[[menu.main]]
name = "Definitions"
weight = 4
url = "/Ddefinitions/"
